---
trust-domain: xpi

task-priority: lowest

taskgraph:
    register: xpi_taskgraph:register
    repositories:
        xpi:
            name: "XPI source"
        template:
            name: "XPI template"
    decision-parameters: 'xpi_taskgraph.parameters:get_decision_parameters'

workers:
    aliases:
        b-linux:
            provisioner: xpi-{level}
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux'
